# Generated by Django 4.1.4 on 2022-12-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=50, verbose_name='Номер')),
                ('level', models.CharField(max_length=6, verbose_name='Класс')),
                ('gosNumber', models.CharField(max_length=9, verbose_name='Гос. номер')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('issueYear', models.IntegerField(verbose_name='Год выпуска')),
            ],
        ),
    ]
