# Generated by Django 4.1.4 on 2022-12-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaxiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='issueYear',
            field=models.DateField(verbose_name='Год выпуска'),
        ),
    ]
