# Generated by Django 4.1.4 on 2022-12-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaxiApp', '0002_alter_vehicles_issueyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='mark',
            field=models.CharField(max_length=50, verbose_name='Марка'),
        ),
    ]
