# Generated by Django 4.1.4 on 2022-12-07 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaxiApp', '0003_alter_vehicles_mark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicles',
            options={'ordering': ['-mark'], 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('lastName', models.CharField(max_length=50, verbose_name='Отчество')),
                ('birthDate', models.DateField(verbose_name='Дата рождения')),
                ('inn', models.IntegerField(verbose_name='ИНН')),
                ('serno', models.CharField(max_length=15, verbose_name='Серно паспорта')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='TaxiApp.vehicles', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
                'ordering': ['surname'],
            },
        ),
    ]
