# Generated by Django 4.1.4 on 2022-12-07 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaxiApp', '0004_alter_vehicles_options_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='level',
        ),
        migrations.CreateModel(
            name='level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='TaxiApp.vehicles', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'ordering': ['level'],
            },
        ),
    ]
