# Generated by Django 4.1.4 on 2022-12-07 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaxiApp', '0005_remove_vehicles_level_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['name'], 'verbose_name': 'Класс', 'verbose_name_plural': 'Классы'},
        ),
        migrations.RemoveField(
            model_name='level',
            name='level',
        ),
        migrations.AddField(
            model_name='level',
            name='name',
            field=models.CharField(db_index=True, default='Unknown', max_length=6, verbose_name='Класс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicles',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='TaxiApp.level', verbose_name='Класс'),
        ),
    ]
