# Generated by Django 4.1.4 on 2022-12-07 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaxiApp', '0007_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='serno',
        ),
    ]
