# Generated by Django 4.1.4 on 2022-12-08 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaxiApp', '0008_remove_order_serno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicles',
            options={'ordering': ['gosNumber'], 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='driver',
        ),
        migrations.AddField(
            model_name='driver',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='TaxiApp.order', verbose_name='Заказ'),
        ),
    ]
