# Generated by Django 4.1.4 on 2022-12-08 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaxiApp', '0009_alter_vehicles_options_remove_order_driver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='TaxiApp.driver', verbose_name='Водитель'),
        ),
    ]
